version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-stretch-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker

      - restore_cache:
          keys:
            - node-10-dependencies-{{ checksum "package-lock.json" }}

      - run: npm version
      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: node-10-dependencies-{{ checksum "package-lock.json" }}

      - run: npm run test:unit

      - run: npm run build
      - run: tar -zcvf dist.tar.gz ./dist

      - run: npm run build-no-auth
      - run: tar -zcvf dist-no-auth.tar.gz ./dist-no-auth

      # build and push Docker image tagged with build-num, latest and branch name
      - run: |
          BUILD_TAG=commit-$CIRCLE_SHA1
          docker build . -t solostec/smf:$BUILD_TAG -f docker/Dockerfile
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          for tag in {build-$CIRCLE_BUILD_NUM,latest,$CIRCLE_BRANCH}; do
            docker tag solostec/smf:$BUILD_TAG solostec/smf:${tag}
            docker push solostec/smf:${tag}
          done

      - store_artifacts:
          path: ~/repo/coverage

      - store_artifacts:
          path: ~/repo/dist.tar.gz

      - store_artifacts:
          path: ~/repo/dist-no-auth.tar.gz
