version: 2.1

# Most jobs will inherit these defaults
var_1: &job_defaults
  working_directory: ~/repo
  docker:
    # Use the -browsers version just to get the right .so files on the disk
    - image: circleci/node:14-stretch-browsers
      environment:
        CHROME_BIN: "/usr/bin/google-chrome"

references:
  workspace_root: &workspace_root
                    .
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root


jobs:
  test-dash:
    <<: *job_defaults
    steps:
      - checkout
      - *attach_workspace
      - run: npm version
      - run: npm ci
      - run: npm run test:unit
      - store_artifacts:
          path: ~/repo/coverage
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - node_modules
  build-dash:
    <<: *job_defaults
    steps:
      - checkout
      - *attach_workspace
      - run: npm run build
      - run: tar -zcvf dist.tar.gz ./dist
      - store_artifacts:
          path: ~/repo/dist.tar.gz

  build-no-auth-dash:
    <<: *job_defaults
    steps:
      - checkout
      - *attach_workspace
      - run: npm run build-no-auth
      - run: tar -zcvf dist-no-auth.tar.gz ./dist-no-auth
      - store_artifacts:
          path: ~/repo/dist-no-auth.tar.gz

  dockerize:
    docker:
      - image: circleci/node:10-stretch-browsers
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout
      - *attach_workspace
      # build and push Docker image tagged with build-num, latest (only if branch is master) and branch name
      - run: |
          BUILD_TAG=commit-$CIRCLE_SHA1
          if [ "${CIRCLE_BRANCH}" == "master" ];
          then
            NPM_BUILD_COMMAND=build-docker
          else
            NPM_BUILD_COMMAND=build-docker-dev
          fi
          docker build . --build-arg NPM_BUILD_COMMAND=$NPM_BUILD_COMMAND -t solostec/dashboard:$BUILD_TAG -f docker/Dockerfile
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          for tag in {build-$CIRCLE_BUILD_NUM,$CIRCLE_BRANCH}; do
            docker tag solostec/dashboard:$BUILD_TAG solostec/dashboard:${tag}
            docker push solostec/dashboard:${tag}
          done
          if [ "${CIRCLE_BRANCH}" == "master" ];
          then
            docker tag solostec/dashboard:$BUILD_TAG solostec/dashboard:latest
            docker push solostec/dashboard:latest
          fi

  deploy:
    docker:
      - image: cimg/base:2020.01
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "52:21:f2:c8:77:89:f2:61:65:0f:5b:5b:08:50:a6:b6"
      - run: ssh -o StrictHostKeyChecking=no -t smf.solostec.net /opt/smf/deploy.sh
      - run: "curl -u $CIRCLE_CI_2_CIRCLE_CI_TOKEN: -X POST https://circleci.com/api/v2/project/gh/solosTec/segw-build/pipeline --header \"Content-Type: application/json\" -d '{ \"parameters\": { \"start_at\": \"dist\" } }'"

workflows:
  version: 2
  build-and-push-on-commit:
    jobs:
      - test-dash
      - build-dash:
          requires:
            - test-dash
      - build-no-auth-dash:
          requires:
            - test-dash
      - dockerize:
          requires:
            - test-dash
      - deploy:
          requires:
            - dockerize
